FROM node:24-alpine

WORKDIR /workspace

RUN npm install --global pnpm

COPY package.json ./
COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY turbo.json ./

COPY apps ./apps
COPY packages ./packages

RUN pnpm install --frozen-lockfile
RUN pnpm --filter @currency/shared build

CMD ["sh"]
